name: 'imagedream-sir'
stage: geo_tex
fp16: True
batch_size: # fromimmagedream config
test: False
guidance:
  name: imagedream
  guidance_scale: 3.0
  denoise_steps: 25
  t2_schedule: [0.8, 0.6]
  t1_ratio: 0.6
  ddim_eta: 0.0
model:
  lock_geo: False
  lock_tex: False
  skip_bg: True
  init_empty_tex: True
  albedo_res: 1024
  mesh: data/init_body/fit_smplx_dense.obj
  init_with_tpose: True
training:
  anneal_tex_reso: True
  anneal_tex_reso_size: 128
  train_face_ratio: 0.0
  train_face_scale: 1.4
  iters: 3000
  iters_per_epoch: 60
  sir_recon_iters: 15
  eval_interval: 10
  save_image_interval: 100
  ckpt: scratch
  workspace: "output"
  use_dpt: True
  use_isnet: True
  use_lpips: True
  strategy: 'sir'
  lambda_lpips: 0.01
  lambda_rgb: 0.8
  lambda_mask: 0.04
  lambda_normal: 0.4
data:
  phi_range: [-180, 180] # dummy
  theta_range: [85, 90] # dummy
  head_phi_range: [-30, 30] # dummy
  head_theta_range: [75, 85] # dummy
