name: 'imagedream'
stage: geo_tex
batch_size: # fromimmagedream config
test: False
guidance:
  name: imagedream
model:
  lock_geo: False
  lock_tex: False
  skip_bg: True
  init_empty_tex: True
  albedo_res: 2048
  mesh: data/init_body/fit_smplx_dense.obj
  init_with_tpose: True
training:
  anneal_tex_reso: True
  train_face_ratio: 0.0
  iters: 15000
  ckpt: scratch
  workspace: "output"
  use_dpt: True
data:
  phi_range: [-180, 180] # dummy
  theta_range: [85, 90] # dummy
  head_phi_range: [-30, 30] # dummy
  head_theta_range: [75, 85] # dummy
